from PIL import Image, ImageFilter

img = Image.open("C:\\Users\\burnk\\OneDrive\\Pictures\\Anime\\anime girl with animal ear.jpg")
# img.save(f"Mini_Projects/Water Tracker/Assets/Images/Logo/logo_Water Intak1.png")
img1 = img.rotate(90)
# img1.show()
img2 = img.convert(mode='L')
# img2.show()
img3 = img.resize(size=(50, 50))
# img3.show()
img4 = img.crop((100,200,230,400))
# img4.show()
img5 = img.filter(ImageFilter.GaussianBlur(radius=5))
img5.show()
img6 = img.transpose(Image.FLIP_TOP_BOTTOM)
# img6.show()
print("Image format:", img.format)
print("Image size:", img.size)
print("Image mode:", img.mode)
# img.show()