import turtle
main = turtle.Turtle()
turtle.setup(1000, 1000)

main.color('black', "white")
main.begin_fill()
main.forward(200)
main.left(90)
main.forward(80)
main.left(90)
main.forward(400)
main.left(90)
main.forward(80)
main.left(90)
main.forward(200)
main.end_fill()

main.color('black', "green")
main.begin_fill()
main.forward(200)
main.right(90)
main.forward(80)
main.right(90)
main.forward(400)
main.right(90)
main.forward(80)
main.end_fill()
main.forward(80)

main.color('black', "orange")
main.begin_fill()
main.forward(80)
main.right(90)
main.forward(400)
main.right(90)
main.forward(80)
main.end_fill()

main.right(90)
main.forward(200)

main.color("black",'blue')
main.begin_fill()
main.circle(40)
main.end_fill()
turtle.done()