string = "I'm BurnKnuckle"
centered = string.center(120)
print(centered)
count = string.count("Burn")
print(count)
count = string.count("n", 4, 10)
print(count)
end  = string.endswith("kle")
print(end)
find = string.find("Bur")
print(find)
find = string.find("r",4, 10)
print(find)
print(string[find])
print(string.isalpha())
print(string.isdigit())
seq = [" Hero ", "  Pro "]
print(string.join(seq))
print(string.lower())
print(string.upper())
print(string.replace("Burn", "Burn ", 1))
print(string.replace("n", "N ", 1))
print(string.split(" "))
print(string.startswith("I"))
print(string.strip())
print(string.strip("I'm "))